import Foundation

nonisolated func appLocalizedString(_ key: String) -> String {
  let languageCode = LanguageManager.storedOrDefaultLanguageCode()
  let locale = appLocalizationLocale(languageCode: languageCode)
  var resource = LocalizedStringResource(
    String.LocalizationValue(key),
    table: nil,
    locale: locale,
    bundle: Bundle.main,
    comment: nil
  )
  resource.locale = locale
  return String(localized: resource)
}

nonisolated func appLocalizedString(_ key: String, arguments: CVarArg...) -> String {
  let locale = appLocalizationLocale(languageCode: LanguageManager.storedOrDefaultLanguageCode())
  let format = appLocalizedString(key)
  return String(format: format, locale: locale, arguments: arguments)
}

nonisolated func localizedString(_ key: String, languageCode: String) -> String {
  let locale = appLocalizationLocale(languageCode: languageCode)
  var resource = LocalizedStringResource(
    String.LocalizationValue(key),
    table: nil,
    locale: locale,
    bundle: Bundle.main,
    comment: nil
  )
  resource.locale = locale
  return String(localized: resource)
}

nonisolated func localizedString(_ key: String, languageCode: String, arguments: CVarArg...) -> String {
  let locale = appLocalizationLocale(languageCode: languageCode)
  let format = localizedString(key, languageCode: languageCode)
  return String(format: format, locale: locale, arguments: arguments)
}

nonisolated private func appLocalizationLocale(languageCode: String) -> Locale {
  LanguageManager.locale(forLanguageCode: languageCode, regionLocale: .autoupdatingCurrent)
}

// MARK: - Localization Keys
struct Localizable {
  private init() {}

  static let accessibilityMenuButton = "accessibility_menu_button"
  static let accessibilityMenuButtonHint = "accessibility_menu_button_hint"
  static let accessibilitySaveButton = "accessibility_save_button"
  static let accessibilitySaveButtonHint = "accessibility_save_button_hint"
  static let addEntry = "add_entry"
  static let aiAnalysis = "ai_analysis"
  static let aiSettingsDepthAskWhatMatters = "ai_settings.depth.ask_what_matters"
  static let aiSettingsDepthCalmMeFirst = "ai_settings.depth.calm_me_first"
  static let aiSettingsDepthGiveMeNextSteps = "ai_settings.depth.give_me_next_steps"
  static let aiSettingsDepthHelpMeSeeItDifferently = "ai_settings.depth.help_me_see_it_differently"
  static let aiSettingsDepthHelpMeUnderstandIt = "ai_settings.depth.help_me_understand_it"
  static let aiSettingsDepthShowMeThePattern = "ai_settings.depth.show_me_the_pattern"
  static let aiSettingsGoalFeelClearer = "ai_settings.goal.feel_clearer"
  static let aiSettingsGoalFeelLessAloneWithIt = "ai_settings.goal.feel_less_alone_with_it"
  static let aiSettingsGoalKnowWhatToDoNext = "ai_settings.goal.know_what_to_do_next"
  static let aiSettingsGoalSleepWithQuieterMind = "ai_settings.goal.sleep_with_quieter_mind"
  static let aiSettingsGoalSpotMyPatterns = "ai_settings.goal.spot_my_patterns"
  static let aiSettingsGoalStopReplayingThings = "ai_settings.goal.stop_replaying_things"
  static let aiSettingsGoalUnderstandMyFeelings = "ai_settings.goal.understand_my_feelings"
  static let aiSettingsPrimaryGoals = "ai_settings.primary_goals"
  static let aiSettingsPrimaryGoalsDescription = "ai_settings.primary_goals.description"
  static let aiSettingsStyleCalming = "ai_settings.style.calming"
  static let aiSettingsStyleClear = "ai_settings.style.clear"
  static let aiSettingsStyleGentle = "ai_settings.style.gentle"
  static let aiSettingsStylePractical = "ai_settings.style.practical"
  static let aiSettingsStyleSoftButDirect = "ai_settings.style.soft_but_direct"
  static let aiSettingsStyleWarm = "ai_settings.style.warm"
  static let aiSettingsSupportDepth = "ai_settings.support_depth"
  static let aiSettingsSupportDepthDescription = "ai_settings.support_depth.description"
  static let aiSettingsSupportStyle = "ai_settings.support_style"
  static let aiSettingsSupportStyleDescription = "ai_settings.support_style.description"
  static let aiSettingsTitle = "ai_settings.title"
  static let analyticsAIResponses = "analytics_ai_responses"
  static let analyticsAvgReflectionDepth = "analytics_avg_reflection_depth"
  static let analyticsDayShort = "analytics_day_short"
  static let analyticsHours = "analytics_hours"
  static let analyticsLast30Days = "analytics_last_30_days"
  static let analyticsMinutes = "analytics_minutes"
  static let analyticsMostReflectiveDay = "analytics_most_reflective_day"
  static let analyticsMostReflectiveTime = "analytics_most_reflective_time"
  static let analyticsNoData = "analytics_no_data"
  static let analyticsReflectingSince = "analytics_reflecting_since"
  static let analyticsReflections = "analytics_reflections"
  static let analyticsStreak = "analytics_streak"
  static let analyticsTimeAfternoon = "analytics_time_afternoon"
  static let analyticsTimeEvening = "analytics_time_evening"
  static let analyticsTimeMorning = "analytics_time_morning"
  static let analyticsTimeNight = "analytics_time_night"
  static let analyticsTimeReflecting = "analytics_time_reflecting"
  static let analyticsTimeSpent = "analytics_time_spent"
  static let analyticsTotalEntries = "analytics_total_entries"
  static let analyticsWordsWritten = "analytics_words_written"
  static let appName = "app_name"
  static let cancel = "cancel"
  static let cannotSummarizeEmpty = "cannot_summarize_empty"
  static let changeDate = "change_date"
  static let contact = "contact"
  static let contactUsIncludeLogs = "contact_us_include_logs"
  static let contactUsIncludeLogsDesc = "contact_us_include_logs_desc"
  static let contactUsMessageLabel = "contact_us_message_label"
  static let contactUsMessagePlaceholder = "contact_us_message_placeholder"
  static let contactUsSend = "contact_us_send"
  static let contactUsSubtitle = "contact_us_subtitle"
  static let contactUsTitle = "contact_us_title"
  static let dataSection = "data_section"
  static let delete = "delete"
  static let deleteEntry = "delete_entry"
  static let deleteEntryMessage = "delete_entry_message"
  static let deleteEntryTitle = "delete_entry_title"
  static let discoverPatterns = "discover_patterns"
  static let discoverPatternsAndInsights = "discover_patterns_and_insights"
  static let done = "done"
  static let emptyStateDescription = "empty_state_description"
  static let emptyStateTitle = "empty_state_title"
  static let entryText = "entry_text"
  static let errorAIService = "error_ai_service"
  static let errorDailyLimitReached = "error_daily_limit_reached"
  static let errorNetwork = "error_network"
  static let errorRateLimited = "error_rate_limited"
  static let exportEntries = "export_entries"
  static let exportError = "export_error"
  static let exportSuccess = "export_success"
  static let failedToSummarize = "failed_to_summarize"
  static let importConfirmAction = "import_confirm_action"
  static let importConfirmMessage = "import_confirm_message"
  static let importConfirmTitle = "import_confirm_title"
  static let importEntries = "import_entries"
  static let importEntriesImported = "import_entries_imported"
  static let importEntriesImportedSkipped = "import_entries_imported_skipped"
  static let importError = "import_error"
  static let importSuccess = "import_success"
  static let journalEntry = "journal_entry"
  static let lastWeek = "last_week"
  static let language = "language"
  static let currentLanguage = "current_language"
  static let languageSettingsInfo = "language_settings_info"

  // MARK: Theme
  static let themeSettingsTitle = "theme.settings.title"
  static let themeSettingsDescription = "theme.settings.description"
  static let themeVariantParchment = "theme.variant.parchment"
  static let themeVariantInk = "theme.variant.ink"
  static let themeVariantSage = "theme.variant.sage"
  static let themeVariantDusk = "theme.variant.dusk"
  static let themeVariantIris = "theme.variant.iris"
  static let themeVariantBlush = "theme.variant.blush"
  static let legal = "legal"
  static let next = "next"
  static let noEntriesYet = "no_entries_yet"
  static let notePlaceholder = "note_placeholder"
  static let notePlaceholderInitial = "note_placeholder_initial"

  // MARK: - Entry Prompts (cards above textarea)

  // Category titles
  static let promptsCategoryMorningTitle = "prompts.category.morning.title"
  static let promptsCategoryEveningTitle = "prompts.category.evening.title"
  static let promptsCategoryLateNightTitle = "prompts.category.late_night.title"
  static let promptsCategoryStuckTitle = "prompts.category.stuck.title"
  static let promptsCategoryReplayTitle = "prompts.category.replay.title"
  static let promptsCategoryHeavyTitle = "prompts.category.heavy.title"
  static let promptsCategoryFrustratedTitle = "prompts.category.frustrated.title"
  static let promptsCategoryNumbTitle = "prompts.category.numb.title"
  static let promptsCategoryAnxiousTitle = "prompts.category.anxious.title"
  static let promptsCategoryRestlessTitle = "prompts.category.restless.title"
  static let promptsCategoryDecisionTitle = "prompts.category.decision.title"
  static let promptsCategorySomeoneTitle = "prompts.category.someone.title"
  static let promptsCategoryYouVsThemTitle = "prompts.category.you_vs_them.title"
  static let promptsCategoryChangeTitle = "prompts.category.change.title"
  static let promptsCategoryWinsTitle = "prompts.category.wins.title"
  static let promptsCategoryGratitudeTitle = "prompts.category.gratitude.title"
  static let promptsCategoryPatternsTitle = "prompts.category.patterns.title"
  static let promptsCategoryFutureSelfTitle = "prompts.category.future_self.title"
  static let promptsCategoryReturningTitle = "prompts.category.returning.title"
  static let promptsCategoryContinueTitle = "prompts.category.continue.title"
  static let promptsCategoryBrainDumpTitle = "prompts.category.brain_dump.title"

  // Accessibility hint for the cards
  static let promptsCardAccessibilityHint = "prompts.card.accessibility_hint"

  // Cluster titles (user-visible cards on the rail)
  static let promptsClusterTimeTitleMorning = "prompts.cluster.time.title.morning"
  static let promptsClusterTimeTitleEvening = "prompts.cluster.time.title.evening"
  static let promptsClusterTimeTitleLateNight = "prompts.cluster.time.title.late_night"
  static let promptsClusterHeavyTitle = "prompts.cluster.heavy.title"
  static let promptsClusterLoopingTitle = "prompts.cluster.looping.title"
  static let promptsClusterSomeoneTitle = "prompts.cluster.someone.title"
  static let promptsClusterChoosingTitle = "prompts.cluster.choosing.title"
  static let promptsClusterNoticeTitle = "prompts.cluster.notice.title"
  static let promptsClusterBrainDumpTitle = "prompts.cluster.brain_dump.title"
  nonisolated static let notificationFollowUpFallback = "notification.follow_up.fallback"
  nonisolated static let notificationReEngagementFallback = "notification.re_engagement.fallback"
  static let notifications = "notifications"
  static let notificationsDisabled = "notifications_disabled"
  static let notificationsDisabledMessage = "notifications_disabled_message"
  static let notificationSettings = "notification_settings"
  static let notificationsTypeConversationFollowUpDescription = "notifications.type.conversation_follow_up.description"
  static let notificationsTypeConversationFollowUpTitle = "notifications.type.conversation_follow_up.title"
  static let notificationsTypeMorningReminderDescription = "notifications.type.morning_reminder.description"
  static let notificationsTypeMorningReminderTitle = "notifications.type.morning_reminder.title"
  static let notificationsTypeEveningReminderDescription = "notifications.type.evening_reminder.description"
  static let notificationsTypeEveningReminderTitle = "notifications.type.evening_reminder.title"
  static let notificationsTypeReEngagementDescription = "notifications.type.re_engagement.description"
  static let notificationsTypeReEngagementTitle = "notifications.type.re_engagement.title"
  static let ok = "ok"
  static let onboardingWriteHere = "onboarding_write_here"

  // MARK: - Onboarding Flow (Phase 1)
  static let onboardingFlowHey = "onboarding_flow.hey"
  static let onboardingFlowTapToContinue = "onboarding_flow.tap_to_continue"
  static let onboardingFlowVP1Headline = "onboarding_flow.vp1.headline"
  static let onboardingFlowVP1Highlight = "onboarding_flow.vp1.highlight"
  static let onboardingFlowVP1Body1 = "onboarding_flow.vp1.body1"
  static let onboardingFlowVP1Body2 = "onboarding_flow.vp1.body2"
  static let onboardingFlowVP1Body3 = "onboarding_flow.vp1.body3"
  static let onboardingFlowVP2Headline = "onboarding_flow.vp2.headline"
  static let onboardingFlowVP2Highlight = "onboarding_flow.vp2.highlight"
  static let onboardingFlowVP2Subtitle = "onboarding_flow.vp2.subtitle"
  static let onboardingFlowVP2SubtitleHighlight = "onboarding_flow.vp2.subtitle_highlight"
  static let onboardingFlowVP2Body1 = "onboarding_flow.vp2.body1"
  static let onboardingFlowVP2Body2 = "onboarding_flow.vp2.body2"
  static let onboardingFlowVP2Body3 = "onboarding_flow.vp2.body3"
  static let onboardingFlowVP2Body3Highlight = "onboarding_flow.vp2.body3_highlight"
  static let onboardingFlowFirstThingsFirst = "onboarding_flow.first_things_first"
  static let onboardingFlowNameQuestion = "onboarding_flow.name_question"
  static let onboardingFlowNameFallback = "onboarding_flow.name_fallback"
  static let onboardingFlowContinue = "onboarding_flow.continue"
  static let onboardingFlowConsiderLine1 = "onboarding_flow.consider_line1"
  static let onboardingFlowConsiderLine2 = "onboarding_flow.consider_line2"

  // MARK: - Onboarding Flow (Phase 2 — Survey, Screens 6-9)

  // Screen 6: Thought type
  static let onboardingFlowSurveyThoughtQuestion = "onboarding_flow.survey.thought_question"
  static let onboardingFlowSurveyThoughtQuestionHighlight = "onboarding_flow.survey.thought_question_highlight"
  static let onboardingFlowSurveyThoughtSomeone = "onboarding_flow.survey.thought.someone"
  static let onboardingFlowSurveyThoughtWhatHappened = "onboarding_flow.survey.thought.what_happened"
  static let onboardingFlowSurveyThoughtSomethingIDid = "onboarding_flow.survey.thought.something_i_did"
  static let onboardingFlowSurveyThoughtWhatToDo = "onboarding_flow.survey.thought.what_to_do"
  static let onboardingFlowSurveyThoughtFeeling = "onboarding_flow.survey.thought.feeling"
  static let onboardingFlowSurveyThoughtMyself = "onboarding_flow.survey.thought.myself"

  // Screen 7: Combined frequency + duration pattern
  static let onboardingFlowSurveyPatternQuestion = "onboarding_flow.survey.pattern_question"
  static let onboardingFlowSurveyPatternAllTheTime = "onboarding_flow.survey.pattern.all_the_time"
  static let onboardingFlowSurveyPatternPrettyOften = "onboarding_flow.survey.pattern.pretty_often"
  static let onboardingFlowSurveyPatternSometimes = "onboarding_flow.survey.pattern.sometimes"
  static let onboardingFlowSurveyPatternNotMuch = "onboarding_flow.survey.pattern.not_much"
  static let onboardingFlowSurveyPatternRarely = "onboarding_flow.survey.pattern.rarely"

  // Screen 8: Empathy calculation
  static let onboardingFlowEmpathyYoullSpend = "onboarding_flow.empathy.youll_spend"
  static let onboardingFlowEmpathyHoursThisYear = "onboarding_flow.empathy.hours_this_year"
  static let onboardingFlowEmpathyThats = "onboarding_flow.empathy.thats"
  static let onboardingFlowEmpathyDays = "onboarding_flow.empathy.days"
  static let onboardingFlowEmpathyQuestion = "onboarding_flow.empathy.question"
  static let onboardingFlowEmpathyQuestionHighlight = "onboarding_flow.empathy.question_highlight"
  static let onboardingFlowEmpathyVerbDefault = "onboarding_flow.empathy.verb.default"
  static let onboardingFlowEmpathyVerbSomeone = "onboarding_flow.empathy.verb.someone"
  static let onboardingFlowEmpathyVerbWhatHappened = "onboarding_flow.empathy.verb.what_happened"
  static let onboardingFlowEmpathyVerbSomethingIDid = "onboarding_flow.empathy.verb.something_i_did"
  static let onboardingFlowEmpathyVerbWhatToDo = "onboarding_flow.empathy.verb.what_to_do"
  static let onboardingFlowEmpathyVerbFeeling = "onboarding_flow.empathy.verb.feeling"
  static let onboardingFlowEmpathyVerbMyself = "onboarding_flow.empathy.verb.myself"

  // Screen 9: Hope
  static let onboardingFlowHopeLine1 = "onboarding_flow.hope.line1"
  static let onboardingFlowHopeLine2 = "onboarding_flow.hope.line2"
  static let onboardingFlowHopeLine2Highlight1 = "onboarding_flow.hope.line2_highlight1"
  static let onboardingFlowHopeLine2Highlight2 = "onboarding_flow.hope.line2_highlight2"
  static let onboardingFlowHopeLine3 = "onboarding_flow.hope.line3"

  // MARK: - Onboarding Flow (Phase 3 — Goals & Vision, Screens 11-13)

  // Screen 11: Goals
  static let onboardingFlowGoalQuestion = "onboarding_flow.goal.question"
  static let onboardingFlowGoalSubtitle = "onboarding_flow.goal.subtitle"
  static let onboardingFlowGoalFeelClearer = "onboarding_flow.goal.feel_clearer"
  static let onboardingFlowGoalStopReplaying = "onboarding_flow.goal.stop_replaying"
  static let onboardingFlowGoalUnderstandFeelings = "onboarding_flow.goal.understand_feelings"
  static let onboardingFlowGoalKnowWhatToDo = "onboarding_flow.goal.know_what_to_do"
  static let onboardingFlowGoalSleepQuieter = "onboarding_flow.goal.sleep_quieter"
  static let onboardingFlowGoalFeelLessAlone = "onboarding_flow.goal.feel_less_alone"
  static let onboardingFlowGoalSpotPatterns = "onboarding_flow.goal.spot_patterns"

  // Screen 11: Goal descriptions (for screen 13 cards)
  static let onboardingFlowGoalDescFeelClearer = "onboarding_flow.goal.desc.feel_clearer"
  static let onboardingFlowGoalDescStopReplaying = "onboarding_flow.goal.desc.stop_replaying"
  static let onboardingFlowGoalDescUnderstandFeelings = "onboarding_flow.goal.desc.understand_feelings"
  static let onboardingFlowGoalDescKnowWhatToDo = "onboarding_flow.goal.desc.know_what_to_do"
  static let onboardingFlowGoalDescSleepQuieter = "onboarding_flow.goal.desc.sleep_quieter"
  static let onboardingFlowGoalDescFeelLessAlone = "onboarding_flow.goal.desc.feel_less_alone"
  static let onboardingFlowGoalDescSpotPatterns = "onboarding_flow.goal.desc.spot_patterns"

  // Screen 12: Vision
  static let onboardingFlowVisionQuestion = "onboarding_flow.vision.question"
  static let onboardingFlowVisionQuestionHighlight = "onboarding_flow.vision.question_highlight"
  static let onboardingFlowVisionTrusting = "onboarding_flow.vision.trusting"
  static let onboardingFlowVisionNaming = "onboarding_flow.vision.naming"
  static let onboardingFlowVisionComingBack = "onboarding_flow.vision.coming_back"
  static let onboardingFlowVisionReplying = "onboarding_flow.vision.replying"
  static let onboardingFlowVisionSleeping = "onboarding_flow.vision.sleeping"
  static let onboardingFlowVisionStaying = "onboarding_flow.vision.staying"

  // Screen 13: Personalized plan
  static let onboardingFlowPlanFooterTitle = "onboarding_flow.plan.footer_title"
  static let onboardingFlowPlanFooterBody = "onboarding_flow.plan.footer_body"

  // MARK: - Onboarding Flow (Phase 4 — Deep Dive, Screens 14-18)

  // Screen 14: Feeling
  static let onboardingFlowFeelingQuestion = "onboarding_flow.feeling.question"
  static let onboardingFlowFeelingQuestionHighlight = "onboarding_flow.feeling.question_highlight"
  static let onboardingFlowFeelingKeepsLooping = "onboarding_flow.feeling.keeps_looping"
  static let onboardingFlowFeelingUnresolved = "onboarding_flow.feeling.unresolved"
  static let onboardingFlowFeelingHardToExplain = "onboarding_flow.feeling.hard_to_explain"
  static let onboardingFlowFeelingStillHurts = "onboarding_flow.feeling.still_hurts"
  static let onboardingFlowFeelingMessy = "onboarding_flow.feeling.messy"
  static let onboardingFlowFeelingLoudAtNight = "onboarding_flow.feeling.loud_at_night"

  // Screen 15: Blocker
  static let onboardingFlowBlockerQuestion = "onboarding_flow.blocker.question"
  static let onboardingFlowBlockerQuestionHighlight = "onboarding_flow.blocker.question_highlight"
  static let onboardingFlowBlockerNoClearAnswer = "onboarding_flow.blocker.no_clear_answer"
  static let onboardingFlowBlockerThingsUnsaid = "onboarding_flow.blocker.things_unsaid"
  static let onboardingFlowBlockerWhatIfs = "onboarding_flow.blocker.what_ifs"
  static let onboardingFlowBlockerSolveAlone = "onboarding_flow.blocker.solve_alone"
  static let onboardingFlowBlockerRereading = "onboarding_flow.blocker.rereading"
  static let onboardingFlowBlockerWaiting = "onboarding_flow.blocker.waiting"

  // Screen 16: Underneath
  static let onboardingFlowUnderneathQuestion = "onboarding_flow.underneath.question"
  static let onboardingFlowUnderneathQuestionHighlight = "onboarding_flow.underneath.question_highlight"
  static let onboardingFlowUnderneathReassurance = "onboarding_flow.underneath.reassurance"
  static let onboardingFlowUnderneathClosure = "onboarding_flow.underneath.closure"
  static let onboardingFlowUnderneathHeard = "onboarding_flow.underneath.heard"
  static let onboardingFlowUnderneathDoubting = "onboarding_flow.underneath.doubting"
  static let onboardingFlowUnderneathHurt = "onboarding_flow.underneath.hurt"
  static let onboardingFlowUnderneathMakeSense = "onboarding_flow.underneath.make_sense"

  // Screen 17: Help
  static let onboardingFlowHelpQuestion = "onboarding_flow.help.question"
  static let onboardingFlowHelpQuestionHighlight = "onboarding_flow.help.question_highlight"
  static let onboardingFlowHelpUnderstand = "onboarding_flow.help.understand"
  static let onboardingFlowHelpPutIntoWords = "onboarding_flow.help.put_into_words"
  static let onboardingFlowHelpSlowDown = "onboarding_flow.help.slow_down"
  static let onboardingFlowHelpSeeClearly = "onboarding_flow.help.see_clearly"
  static let onboardingFlowHelpKnowWhatToDo = "onboarding_flow.help.know_what_to_do"
  static let onboardingFlowHelpLeaveTonight = "onboarding_flow.help.leave_tonight"

  // Screen 18: Thank you
  static let onboardingFlowThankYouLine1 = "onboarding_flow.thank_you.line1"
  static let onboardingFlowThankYouLine1Highlight = "onboarding_flow.thank_you.line1_highlight"
  static let onboardingFlowThankYouLine2 = "onboarding_flow.thank_you.line2"
  static let onboardingFlowThankYouLine3 = "onboarding_flow.thank_you.line3"
  static let onboardingFlowThankYouLine3Highlight = "onboarding_flow.thank_you.line3_highlight"
  static let onboardingFlowThankYouLine4 = "onboarding_flow.thank_you.line4"

  // MARK: - Onboarding Flow (Phase 5 — Support & Summary, Screens 19-22)

  // Screen 19: Support style
  static let onboardingFlowStyleQuestion = "onboarding_flow.style.question"
  static let onboardingFlowStyleSubtitle = "onboarding_flow.style.subtitle"
  static let onboardingFlowStyleSubtitleHighlight = "onboarding_flow.style.subtitle_highlight"
  static let onboardingFlowStyleGentle = "onboarding_flow.style.gentle"
  static let onboardingFlowStyleWarm = "onboarding_flow.style.warm"
  static let onboardingFlowStyleCalming = "onboarding_flow.style.calming"
  static let onboardingFlowStyleClear = "onboarding_flow.style.clear"
  static let onboardingFlowStylePractical = "onboarding_flow.style.practical"
  static let onboardingFlowStyleSoftButDirect = "onboarding_flow.style.soft_but_direct"

  // Screen 20: Support depth
  static let onboardingFlowDepthQuestion = "onboarding_flow.depth.question"
  static let onboardingFlowDepthCalmMeFirst = "onboarding_flow.depth.calm_me_first"
  static let onboardingFlowDepthHelpMeUnderstandIt = "onboarding_flow.depth.help_me_understand_it"
  static let onboardingFlowDepthAskWhatMatters = "onboarding_flow.depth.ask_what_matters"
  static let onboardingFlowDepthShowMeThePattern = "onboarding_flow.depth.show_me_the_pattern"
  static let onboardingFlowDepthHelpMeSeeItDifferently = "onboarding_flow.depth.help_me_see_it_differently"
  static let onboardingFlowDepthGiveMeNextSteps = "onboarding_flow.depth.give_me_next_steps"

  // Screen 21: Journey summary
  static let onboardingFlowSummaryTitle = "onboarding_flow.summary.title"
  static let onboardingFlowSummarySubtitle = "onboarding_flow.summary.subtitle"
  static let onboardingFlowSummaryWhereToGo = "onboarding_flow.summary.where_to_go"
  static let onboardingFlowSummaryWhereNow = "onboarding_flow.summary.where_now"
  static let onboardingFlowSummaryStanding = "onboarding_flow.summary.standing"
  static let onboardingFlowSummaryMessage = "onboarding_flow.summary.message"

  // Screen 22: Progress chart
  static let onboardingFlowChartTitle = "onboarding_flow.chart.title"
  static let onboardingFlowChartBody = "onboarding_flow.chart.body"
  static let onboardingFlowChartCTA = "onboarding_flow.chart.cta"
  static let onboardingFlowChartLegendClarity = "onboarding_flow.chart.legend_clarity"
  static let onboardingFlowChartLegendOverthinking = "onboarding_flow.chart.legend_overthinking"
  static let onboardingFlowChartWeek1 = "onboarding_flow.chart.week1"
  static let onboardingFlowChartWeek2 = "onboarding_flow.chart.week2"
  static let onboardingFlowChartWeek3 = "onboarding_flow.chart.week3"

  // MARK: - Onboarding Flow (Phase 6 — Demo & Completion, Screens 23-24)

  // Screen 23: Demo conversation
  static let onboardingFlowDemoWelcome = "onboarding_flow.demo.welcome"
  static let onboardingFlowDemoFooterPrimary = "onboarding_flow.demo.footer_primary"
  static let onboardingFlowDemoFooterSecondary = "onboarding_flow.demo.footer_secondary"

  // Screen 24: Demo complete
  static let onboardingFlowDemoCompleteTitle = "onboarding_flow.demo_complete.title"
  static let onboardingFlowDemoCompleteSubtitle = "onboarding_flow.demo_complete.subtitle"
  static let onboardingFlowDemoCompleteMessage = "onboarding_flow.demo_complete.message"

  // Screen 25: Streak kickoff
  static let onboardingFlowStreakDayLabel = "onboarding_flow.streak.day_label"
  static let onboardingFlowStreakBody = "onboarding_flow.streak.body"

  // MARK: - Onboarding Flow (Phase 8 — Plan & Commitment, Screens 26-30)

  // Screen 26: Plan loading
  static let onboardingFlowPlanLoadingStep1 = "onboarding_flow.plan_loading.step1"
  static let onboardingFlowPlanLoadingStep2 = "onboarding_flow.plan_loading.step2"
  static let onboardingFlowPlanLoadingStep3 = "onboarding_flow.plan_loading.step3"
  static let onboardingFlowPlanLoadingStep4 = "onboarding_flow.plan_loading.step4"
  static let onboardingFlowPlanLoadingStep5 = "onboarding_flow.plan_loading.step5"

  // Screen 27: Plan ready
  static let onboardingFlowPlanReadyHeadline = "onboarding_flow.plan_ready.headline"
  static let onboardingFlowPlanReadyCTA = "onboarding_flow.plan_ready.cta"

  // Screen 28: Clarity plan card
  static let onboardingFlowPlanHeroHeadline = "onboarding_flow.plan.hero_headline"
  static let onboardingFlowPlanStatReflections = "onboarding_flow.plan.stat_reflections"
  static let onboardingFlowPlanStatMornings = "onboarding_flow.plan.stat_mornings"
  static let onboardingFlowPlanStatInsights = "onboarding_flow.plan.stat_insights"
  static let onboardingFlowPlanInvested = "onboarding_flow.plan.invested"
  static let onboardingFlowPlanHowWellGetThere = "onboarding_flow.plan.how_well_get_there"
  static let onboardingFlowPlanMethod1Title = "onboarding_flow.plan.method1_title"
  static let onboardingFlowPlanMethod1Body = "onboarding_flow.plan.method1_body"
  static let onboardingFlowPlanMethod2Title = "onboarding_flow.plan.method2_title"
  static let onboardingFlowPlanMethod2Body = "onboarding_flow.plan.method2_body"
  static let onboardingFlowPlanMethod3Title = "onboarding_flow.plan.method3_title"
  static let onboardingFlowPlanMethod3Body = "onboarding_flow.plan.method3_body"

  // Screen 29: Commitment question
  static let onboardingFlowCommitmentLeadIn = "onboarding_flow.commitment.lead_in"
  static let onboardingFlowCommitmentQuestion = "onboarding_flow.commitment.question"
  static let onboardingFlowCommitmentExtremely = "onboarding_flow.commitment.extremely"
  static let onboardingFlowCommitmentVery = "onboarding_flow.commitment.very"
  static let onboardingFlowCommitmentSomewhat = "onboarding_flow.commitment.somewhat"
  static let onboardingFlowCommitmentLittle = "onboarding_flow.commitment.little"
  static let onboardingFlowCommitmentJustTrying = "onboarding_flow.commitment.just_trying"

  // Screen 30: Commitment message
  static let onboardingFlowCommitmentMsgExtremelyTitle = "onboarding_flow.commitment_msg.extremely.title"
  static let onboardingFlowCommitmentMsgExtremelyBody = "onboarding_flow.commitment_msg.extremely.body"
  static let onboardingFlowCommitmentMsgVeryTitle = "onboarding_flow.commitment_msg.very.title"
  static let onboardingFlowCommitmentMsgVeryBody = "onboarding_flow.commitment_msg.very.body"
  static let onboardingFlowCommitmentMsgSomewhatTitle = "onboarding_flow.commitment_msg.somewhat.title"
  static let onboardingFlowCommitmentMsgSomewhatBody = "onboarding_flow.commitment_msg.somewhat.body"
  static let onboardingFlowCommitmentMsgLittleTitle = "onboarding_flow.commitment_msg.little.title"
  static let onboardingFlowCommitmentMsgLittleBody = "onboarding_flow.commitment_msg.little.body"
  static let onboardingFlowCommitmentMsgJustTryingTitle = "onboarding_flow.commitment_msg.just_trying.title"
  static let onboardingFlowCommitmentMsgJustTryingBody = "onboarding_flow.commitment_msg.just_trying.body"

  static let onboardingFlowDone = "onboarding_flow.done"

  // MARK: - Onboarding Flow (Phase 9 — Notifications, Demo, Trial Reminder)

  // Screen 31: Notifications priming
  static let onboardingFlowNotifPrimingTitle = "onboarding_flow.notif_priming.title"
  static let onboardingFlowNotifPrimingAlertTitle = "onboarding_flow.notif_priming.alert_title"
  static let onboardingFlowNotifPrimingAlertBody = "onboarding_flow.notif_priming.alert_body"
  static let onboardingFlowNotifPrimingAllow = "onboarding_flow.notif_priming.allow"
  static let onboardingFlowNotifPrimingDeny = "onboarding_flow.notif_priming.deny"

  // Screen 32: Try now demo
  static let onboardingFlowTryNowTitle = "onboarding_flow.try_now.title"
  static let onboardingFlowTryNowNoPayment = "onboarding_flow.try_now.no_payment"
  static let onboardingFlowTryNowCTA = "onboarding_flow.try_now.cta"

  // Screen 33: Trial reminder
  static let onboardingFlowTrialReminderTitle = "onboarding_flow.trial_reminder.title"
  static let onboardingFlowTrialReminderNoPayment = "onboarding_flow.trial_reminder.no_payment"
  static let onboardingFlowTrialReminderCTA = "onboarding_flow.trial_reminder.cta"
  static let onboardingFlowTrialReminderDisclosure = "onboarding_flow.trial_reminder.disclosure"

  // Screen 34: Onboarding paywall
  static let onboardingFlowPaywallTitle = "onboarding_flow.paywall.title"
  static let onboardingFlowPaywallTitleBenefits = "onboarding_flow.paywall.title_benefits"
  static let onboardingFlowPaywallTimelineTodayTitle = "onboarding_flow.paywall.timeline.today_title"
  static let onboardingFlowPaywallTimelineTodayBody = "onboarding_flow.paywall.timeline.today_body"
  static let onboardingFlowPaywallTimelineDay2Title = "onboarding_flow.paywall.timeline.day2_title"
  static let onboardingFlowPaywallTimelineDay2Body = "onboarding_flow.paywall.timeline.day2_body"
  static let onboardingFlowPaywallTimelineDay3Title = "onboarding_flow.paywall.timeline.day3_title"
  static let onboardingFlowPaywallTimelineDay3Body = "onboarding_flow.paywall.timeline.day3_body"
  static let onboardingFlowPaywallBadgeTrial = "onboarding_flow.paywall.badge.trial"
  static let onboardingFlowPaywallPriceMonthly = "onboarding_flow.paywall.price.monthly"
  static let onboardingFlowPaywallNoPayment = "onboarding_flow.paywall.no_payment"
  static let onboardingFlowPaywallNoCommitment = "onboarding_flow.paywall.no_commitment"
  static let onboardingFlowPaywallCTAStartTrial = "onboarding_flow.paywall.cta.start_trial"
  static let onboardingFlowPaywallCTAContinue = "onboarding_flow.paywall.cta.continue"
  static let onboardingFlowPaywallCTAStartJourney = "onboarding_flow.paywall.cta.start_journey"
  static let onboardingFlowPaywallDisclosurePerYear = "onboarding_flow.paywall.disclosure.per_year"
  static let onboardingFlowPaywallDisclosurePerMonth = "onboarding_flow.paywall.disclosure.per_month"
  static let onboardingFlowPaywallDisclosureWithTrial = "onboarding_flow.paywall.disclosure.with_trial"
  static let onboardingFlowPaywallDisclosureNoTrial = "onboarding_flow.paywall.disclosure.no_trial"
  // Benefits-list mode (shown when monthly is selected or trial doesn't apply)
  static let onboardingFlowPaywallBenefit1Title = "onboarding_flow.paywall.benefit1.title"
  static let onboardingFlowPaywallBenefit1Body = "onboarding_flow.paywall.benefit1.body"
  static let onboardingFlowPaywallBenefit2Title = "onboarding_flow.paywall.benefit2.title"
  static let onboardingFlowPaywallBenefit2Body = "onboarding_flow.paywall.benefit2.body"
  static let onboardingFlowPaywallBenefit3Title = "onboarding_flow.paywall.benefit3.title"
  static let onboardingFlowPaywallBenefit3Body = "onboarding_flow.paywall.benefit3.body"

  // Footer (shared across try-now / trial-reminder / paywall)
  static let onboardingFlowFooterPricingFull = "onboarding_flow.footer.pricing_full"
  static let onboardingFlowFooterPricingFallback = "onboarding_flow.footer.pricing_fallback"
  static let onboardingFlowFooterPricingPerMonth = "onboarding_flow.footer.pricing_per_month"

  // Plan label override on the onboarding paywall (the existing
  // `premiumAnnual` is "Annual" and is shared with the legacy paywall).
  static let onboardingFlowPaywallPlanYearly = "onboarding_flow.paywall.plan_yearly"

  // MARK: - Onboarding discount paywall + Live Activity
  static let onboardingDiscountActivityHeadline = "onboarding_discount.activity.headline"
  static let onboardingDiscountActivityCta = "onboarding_discount.activity.cta"
  static let onboardingDiscountActivityFinalPurchased = "onboarding_discount.activity.final.purchased"
  static let onboardingDiscountActivityFinalClosed = "onboarding_discount.activity.final.closed"
  static let onboardingDiscountActivityFinalExpired = "onboarding_discount.activity.final.expired"
  static let onboardingDiscountPaywallTitle = "onboarding_discount.paywall.title"
  static let onboardingDiscountPaywallPercentOff = "onboarding_discount.paywall.percent_off"
  static let onboardingDiscountPaywallWarning = "onboarding_discount.paywall.warning"
  static let onboardingDiscountPaywallPriceOnly = "onboarding_discount.paywall.price.only"
  static let onboardingDiscountPaywallPricePerWeek = "onboarding_discount.paywall.price.per_week"
  static let onboardingDiscountPaywallPriceLowest = "onboarding_discount.paywall.price.lowest"
  static let onboardingDiscountPaywallPricePerYear = "onboarding_discount.paywall.price.per_year"
  static let onboardingDiscountPaywallCta = "onboarding_discount.paywall.cta"
  static let openCollection = "open_collection"
  static let openSettings = "open_settings"
  static let preferences = "preferences"
  static let premiumAnnual = "premium_annual"
  static let premiumBenefit1 = "premium_benefit_1"
  static let premiumBenefit2 = "premium_benefit_2"
  static let premiumBenefit3 = "premium_benefit_3"
  static let premiumBilledAnnually = "premium_billed_annually"
  static let premiumBilledMonthly = "premium_billed_monthly"
  static let premiumBillingPerMonth = "premium_billing_per_month"
  static let premiumBillingPerYear = "premium_billing_per_year"
  static let premiumContinueAnnual = "premium_continue_annual"
  static let premiumErrorCancelled = "premium_error_cancelled"
  static let premiumErrorProductNotFound = "premium_error_product_not_found"
  static let premiumErrorPurchaseFailed = "premium_error_purchase_failed"
  static let premiumErrorRestoreFailed = "premium_error_restore_failed"
  static let premiumHeroDefaultSubtitleTrial = "premium_hero_default_subtitle_trial"
  static let premiumHeroDefaultTitle = "premium_hero_default_title"
  static let premiumHeroLimitSubtitleTrial = "premium_hero_limit_subtitle_trial"
  static let premiumHeroLimitTitle = "premium_hero_limit_title"
  static let premiumHeroOnboardingSubtitleTrial = "premium_hero_onboarding_subtitle_trial"
  static let premiumHeroOnboardingTitle = "premium_hero_onboarding_title"
  static let premiumHeroSettingsSubtitleTrial = "premium_hero_settings_subtitle_trial"
  static let premiumHeroSettingsTitle = "premium_hero_settings_title"
  static let premiumJourneyStep1 = "premium_journey_step_1"
  static let premiumJourneyStep2 = "premium_journey_step_2"
  static let premiumJourneyStep3 = "premium_journey_step_3"
  static let premiumJourneyTime1 = "premium_journey_time_1"
  static let premiumJourneyTime2 = "premium_journey_time_2"
  static let premiumJourneyTime3 = "premium_journey_time_3"
  static let premiumManageSubscription = "premium_manage_subscription"
  static let premiumMaybeLater = "premium_maybe_later"
  static let premiumMonthly = "premium_monthly"
  static let premiumMonthlyEquivalent = "premium_monthly_equivalent"
  static let premiumPerMonth = "premium_per_month"
  static let premiumPerYear = "premium_per_year"
  static let premiumPrivacy = "premium_privacy"
  static let premiumProductsUnavailable = "premium_products_unavailable"
  static let premiumResponseLimitReachedDesc = "premium_response_limit_reached_desc"
  static let premiumAIResponsesToday = "premium_ai_responses_today"
  static let premiumRestore = "premium_restore"
  static let premiumSavePercent = "premium_save_percent"
  static let premiumStatusFree = "premium_status_free"
  static let premiumStatusPremium = "premium_status_premium"
  static let premiumSubscribe = "premium_subscribe"
  static let premiumSubscribeMonthly = "premium_subscribe_monthly"
  static let premiumSubscribeToUnlock = "premium_subscribe_to_unlock"
  static let premiumSubscriptionDisclaimer = "premium_subscription_disclaimer"
  static let premiumSubtitle = "premium_subtitle"
  static let premiumTerms = "premium_terms"
  static let premiumTimelineDay3 = "premium_timeline_day3"
  static let premiumTimelineDay3Detail = "premium_timeline_day3_detail"
  static let premiumTimelineDay7 = "premium_timeline_day7"
  static let premiumTimelineDay7Detail = "premium_timeline_day7_detail"
  static let premiumTimelineToday = "premium_timeline_today"
  static let premiumTimelineTodayDetail = "premium_timeline_today_detail"
  static let premiumTitle = "premium_title"
  static let premiumTrialInfoDynamic = "premium_trial_info_dynamic"
  static let premiumTrySevenDaysFree = "premium_try_seven_days_free"
  static let premiumUpgrade = "premium_upgrade"
  static let privacyLocalStorageMessage = "privacy_local_storage_message"
  static let privacyLocalStorageTitle = "privacy_local_storage_title"
  static let privacyPolicy = "privacy_policy"
  static let quantity = "quantity"
  static let rateApp = "rate_app"
  static let recentInsights = "recent_insights"
  static let reflectionsBannerA11y = "reflections_banner_a11y"
  static let reflectionsBestStreak = "reflections_best_streak"
  static let reflectionsCurrentStreak = "reflections_current_streak"
  static let reflectionsDayUnitFew = "reflections_day_unit_few"
  static let reflectionsDayUnitMany = "reflections_day_unit_many"
  static let reflectionsDayUnitOne = "reflections_day_unit_one"
  static let reflectionsLongestStreak = "reflections_longest_streak"
  static let reflectionsNudgeDayOne = "reflections_nudge_day_one"
  static let reflectionsNudgeEarlyMomentum = "reflections_nudge_early_momentum"
  static let reflectionsNudgeFirstTime = "reflections_nudge_first_time"
  static let reflectionsNudgePractice = "reflections_nudge_practice"
  static let reflectionsNudgeReturning = "reflections_nudge_returning"
  static let reflectionsNudgeWeekRhythm = "reflections_nudge_week_rhythm"
  static let reflectionsSeeAll = "reflections_see_all"
  static let reflectionsThisWeek = "reflections_this_week"
  static let reflectionsTitle = "reflections_title"
  static let replyToReflection = "reply_to_reflection"
  static let shareSotie = "share_sotie"
  static let shareText = "share_text"
  static let showOnboarding = "show_onboarding"
  static let statistics = "statistics"
  static let tapPlusToAddFirstEntry = "tap_plus_to_add_first_entry"
  static let termsOfService = "terms_of_service"
  static let thisWeek = "this_week"
  static let today = "today"
  static let unsavedChangesDiscard = "unsaved_changes_discard"
  static let unsavedChangesSave = "unsaved_changes_save"
  static let unsavedChangesTitle = "unsaved_changes_title"

  // MARK: - Finish & Insights
  static let finish = "finish"
  static let insightsGenerating = "insights_generating"
  static let insightsWhatHappened = "insights_what_happened"
  static let insightsWhatsUnderneath = "insights_whats_underneath"
  static let insightsWhatMattersNow = "insights_what_matters_now"
  static let insightsDone = "insights_done"
  static let insightsError = "insights_error"
  static let insightsRetry = "insights_retry"
  static let insightsSkip = "insights_skip"
  static let insightsTitle = "insights_title"
  static let insightsViewMenu = "insights_view_menu"
  static let finishReflection = "finish_reflection"
  static let values = "values"
  static let yesterday = "yesterday"

  // MARK: - Entry Prompts (openers — 210 entries: 21 categories × 10)

  static let promptsOpenersMorning1 = "prompts.openers.morning.1"
  static let promptsOpenersMorning2 = "prompts.openers.morning.2"
  static let promptsOpenersMorning3 = "prompts.openers.morning.3"
  static let promptsOpenersMorning4 = "prompts.openers.morning.4"
  static let promptsOpenersMorning5 = "prompts.openers.morning.5"
  static let promptsOpenersMorning6 = "prompts.openers.morning.6"
  static let promptsOpenersMorning7 = "prompts.openers.morning.7"
  static let promptsOpenersMorning8 = "prompts.openers.morning.8"
  static let promptsOpenersMorning9 = "prompts.openers.morning.9"
  static let promptsOpenersMorning10 = "prompts.openers.morning.10"
  static let promptsOpenersEvening1 = "prompts.openers.evening.1"
  static let promptsOpenersEvening2 = "prompts.openers.evening.2"
  static let promptsOpenersEvening3 = "prompts.openers.evening.3"
  static let promptsOpenersEvening4 = "prompts.openers.evening.4"
  static let promptsOpenersEvening5 = "prompts.openers.evening.5"
  static let promptsOpenersEvening6 = "prompts.openers.evening.6"
  static let promptsOpenersEvening7 = "prompts.openers.evening.7"
  static let promptsOpenersEvening8 = "prompts.openers.evening.8"
  static let promptsOpenersEvening9 = "prompts.openers.evening.9"
  static let promptsOpenersEvening10 = "prompts.openers.evening.10"
  static let promptsOpenersLateNight1 = "prompts.openers.late_night.1"
  static let promptsOpenersLateNight2 = "prompts.openers.late_night.2"
  static let promptsOpenersLateNight3 = "prompts.openers.late_night.3"
  static let promptsOpenersLateNight4 = "prompts.openers.late_night.4"
  static let promptsOpenersLateNight5 = "prompts.openers.late_night.5"
  static let promptsOpenersLateNight6 = "prompts.openers.late_night.6"
  static let promptsOpenersLateNight7 = "prompts.openers.late_night.7"
  static let promptsOpenersLateNight8 = "prompts.openers.late_night.8"
  static let promptsOpenersLateNight9 = "prompts.openers.late_night.9"
  static let promptsOpenersLateNight10 = "prompts.openers.late_night.10"
  static let promptsOpenersStuck1 = "prompts.openers.stuck.1"
  static let promptsOpenersStuck2 = "prompts.openers.stuck.2"
  static let promptsOpenersStuck3 = "prompts.openers.stuck.3"
  static let promptsOpenersStuck4 = "prompts.openers.stuck.4"
  static let promptsOpenersStuck5 = "prompts.openers.stuck.5"
  static let promptsOpenersStuck6 = "prompts.openers.stuck.6"
  static let promptsOpenersStuck7 = "prompts.openers.stuck.7"
  static let promptsOpenersStuck8 = "prompts.openers.stuck.8"
  static let promptsOpenersStuck9 = "prompts.openers.stuck.9"
  static let promptsOpenersStuck10 = "prompts.openers.stuck.10"
  static let promptsOpenersReplay1 = "prompts.openers.replay.1"
  static let promptsOpenersReplay2 = "prompts.openers.replay.2"
  static let promptsOpenersReplay3 = "prompts.openers.replay.3"
  static let promptsOpenersReplay4 = "prompts.openers.replay.4"
  static let promptsOpenersReplay5 = "prompts.openers.replay.5"
  static let promptsOpenersReplay6 = "prompts.openers.replay.6"
  static let promptsOpenersReplay7 = "prompts.openers.replay.7"
  static let promptsOpenersReplay8 = "prompts.openers.replay.8"
  static let promptsOpenersReplay9 = "prompts.openers.replay.9"
  static let promptsOpenersReplay10 = "prompts.openers.replay.10"
  static let promptsOpenersHeavy1 = "prompts.openers.heavy.1"
  static let promptsOpenersHeavy2 = "prompts.openers.heavy.2"
  static let promptsOpenersHeavy3 = "prompts.openers.heavy.3"
  static let promptsOpenersHeavy4 = "prompts.openers.heavy.4"
  static let promptsOpenersHeavy5 = "prompts.openers.heavy.5"
  static let promptsOpenersHeavy6 = "prompts.openers.heavy.6"
  static let promptsOpenersHeavy7 = "prompts.openers.heavy.7"
  static let promptsOpenersHeavy8 = "prompts.openers.heavy.8"
  static let promptsOpenersHeavy9 = "prompts.openers.heavy.9"
  static let promptsOpenersHeavy10 = "prompts.openers.heavy.10"
  static let promptsOpenersFrustrated1 = "prompts.openers.frustrated.1"
  static let promptsOpenersFrustrated2 = "prompts.openers.frustrated.2"
  static let promptsOpenersFrustrated3 = "prompts.openers.frustrated.3"
  static let promptsOpenersFrustrated4 = "prompts.openers.frustrated.4"
  static let promptsOpenersFrustrated5 = "prompts.openers.frustrated.5"
  static let promptsOpenersFrustrated6 = "prompts.openers.frustrated.6"
  static let promptsOpenersFrustrated7 = "prompts.openers.frustrated.7"
  static let promptsOpenersFrustrated8 = "prompts.openers.frustrated.8"
  static let promptsOpenersFrustrated9 = "prompts.openers.frustrated.9"
  static let promptsOpenersFrustrated10 = "prompts.openers.frustrated.10"
  static let promptsOpenersNumb1 = "prompts.openers.numb.1"
  static let promptsOpenersNumb2 = "prompts.openers.numb.2"
  static let promptsOpenersNumb3 = "prompts.openers.numb.3"
  static let promptsOpenersNumb4 = "prompts.openers.numb.4"
  static let promptsOpenersNumb5 = "prompts.openers.numb.5"
  static let promptsOpenersNumb6 = "prompts.openers.numb.6"
  static let promptsOpenersNumb7 = "prompts.openers.numb.7"
  static let promptsOpenersNumb8 = "prompts.openers.numb.8"
  static let promptsOpenersNumb9 = "prompts.openers.numb.9"
  static let promptsOpenersNumb10 = "prompts.openers.numb.10"
  static let promptsOpenersAnxious1 = "prompts.openers.anxious.1"
  static let promptsOpenersAnxious2 = "prompts.openers.anxious.2"
  static let promptsOpenersAnxious3 = "prompts.openers.anxious.3"
  static let promptsOpenersAnxious4 = "prompts.openers.anxious.4"
  static let promptsOpenersAnxious5 = "prompts.openers.anxious.5"
  static let promptsOpenersAnxious6 = "prompts.openers.anxious.6"
  static let promptsOpenersAnxious7 = "prompts.openers.anxious.7"
  static let promptsOpenersAnxious8 = "prompts.openers.anxious.8"
  static let promptsOpenersAnxious9 = "prompts.openers.anxious.9"
  static let promptsOpenersAnxious10 = "prompts.openers.anxious.10"
  static let promptsOpenersRestless1 = "prompts.openers.restless.1"
  static let promptsOpenersRestless2 = "prompts.openers.restless.2"
  static let promptsOpenersRestless3 = "prompts.openers.restless.3"
  static let promptsOpenersRestless4 = "prompts.openers.restless.4"
  static let promptsOpenersRestless5 = "prompts.openers.restless.5"
  static let promptsOpenersRestless6 = "prompts.openers.restless.6"
  static let promptsOpenersRestless7 = "prompts.openers.restless.7"
  static let promptsOpenersRestless8 = "prompts.openers.restless.8"
  static let promptsOpenersRestless9 = "prompts.openers.restless.9"
  static let promptsOpenersRestless10 = "prompts.openers.restless.10"
  static let promptsOpenersDecision1 = "prompts.openers.decision.1"
  static let promptsOpenersDecision2 = "prompts.openers.decision.2"
  static let promptsOpenersDecision3 = "prompts.openers.decision.3"
  static let promptsOpenersDecision4 = "prompts.openers.decision.4"
  static let promptsOpenersDecision5 = "prompts.openers.decision.5"
  static let promptsOpenersDecision6 = "prompts.openers.decision.6"
  static let promptsOpenersDecision7 = "prompts.openers.decision.7"
  static let promptsOpenersDecision8 = "prompts.openers.decision.8"
  static let promptsOpenersDecision9 = "prompts.openers.decision.9"
  static let promptsOpenersDecision10 = "prompts.openers.decision.10"
  static let promptsOpenersSomeone1 = "prompts.openers.someone.1"
  static let promptsOpenersSomeone2 = "prompts.openers.someone.2"
  static let promptsOpenersSomeone3 = "prompts.openers.someone.3"
  static let promptsOpenersSomeone4 = "prompts.openers.someone.4"
  static let promptsOpenersSomeone5 = "prompts.openers.someone.5"
  static let promptsOpenersSomeone6 = "prompts.openers.someone.6"
  static let promptsOpenersSomeone7 = "prompts.openers.someone.7"
  static let promptsOpenersSomeone8 = "prompts.openers.someone.8"
  static let promptsOpenersSomeone9 = "prompts.openers.someone.9"
  static let promptsOpenersSomeone10 = "prompts.openers.someone.10"
  static let promptsOpenersYouVsThem1 = "prompts.openers.you_vs_them.1"
  static let promptsOpenersYouVsThem2 = "prompts.openers.you_vs_them.2"
  static let promptsOpenersYouVsThem3 = "prompts.openers.you_vs_them.3"
  static let promptsOpenersYouVsThem4 = "prompts.openers.you_vs_them.4"
  static let promptsOpenersYouVsThem5 = "prompts.openers.you_vs_them.5"
  static let promptsOpenersYouVsThem6 = "prompts.openers.you_vs_them.6"
  static let promptsOpenersYouVsThem7 = "prompts.openers.you_vs_them.7"
  static let promptsOpenersYouVsThem8 = "prompts.openers.you_vs_them.8"
  static let promptsOpenersYouVsThem9 = "prompts.openers.you_vs_them.9"
  static let promptsOpenersYouVsThem10 = "prompts.openers.you_vs_them.10"
  static let promptsOpenersChange1 = "prompts.openers.change.1"
  static let promptsOpenersChange2 = "prompts.openers.change.2"
  static let promptsOpenersChange3 = "prompts.openers.change.3"
  static let promptsOpenersChange4 = "prompts.openers.change.4"
  static let promptsOpenersChange5 = "prompts.openers.change.5"
  static let promptsOpenersChange6 = "prompts.openers.change.6"
  static let promptsOpenersChange7 = "prompts.openers.change.7"
  static let promptsOpenersChange8 = "prompts.openers.change.8"
  static let promptsOpenersChange9 = "prompts.openers.change.9"
  static let promptsOpenersChange10 = "prompts.openers.change.10"
  static let promptsOpenersWins1 = "prompts.openers.wins.1"
  static let promptsOpenersWins2 = "prompts.openers.wins.2"
  static let promptsOpenersWins3 = "prompts.openers.wins.3"
  static let promptsOpenersWins4 = "prompts.openers.wins.4"
  static let promptsOpenersWins5 = "prompts.openers.wins.5"
  static let promptsOpenersWins6 = "prompts.openers.wins.6"
  static let promptsOpenersWins7 = "prompts.openers.wins.7"
  static let promptsOpenersWins8 = "prompts.openers.wins.8"
  static let promptsOpenersWins9 = "prompts.openers.wins.9"
  static let promptsOpenersWins10 = "prompts.openers.wins.10"
  static let promptsOpenersGratitude1 = "prompts.openers.gratitude.1"
  static let promptsOpenersGratitude2 = "prompts.openers.gratitude.2"
  static let promptsOpenersGratitude3 = "prompts.openers.gratitude.3"
  static let promptsOpenersGratitude4 = "prompts.openers.gratitude.4"
  static let promptsOpenersGratitude5 = "prompts.openers.gratitude.5"
  static let promptsOpenersGratitude6 = "prompts.openers.gratitude.6"
  static let promptsOpenersGratitude7 = "prompts.openers.gratitude.7"
  static let promptsOpenersGratitude8 = "prompts.openers.gratitude.8"
  static let promptsOpenersGratitude9 = "prompts.openers.gratitude.9"
  static let promptsOpenersGratitude10 = "prompts.openers.gratitude.10"
  static let promptsOpenersPatterns1 = "prompts.openers.patterns.1"
  static let promptsOpenersPatterns2 = "prompts.openers.patterns.2"
  static let promptsOpenersPatterns3 = "prompts.openers.patterns.3"
  static let promptsOpenersPatterns4 = "prompts.openers.patterns.4"
  static let promptsOpenersPatterns5 = "prompts.openers.patterns.5"
  static let promptsOpenersPatterns6 = "prompts.openers.patterns.6"
  static let promptsOpenersPatterns7 = "prompts.openers.patterns.7"
  static let promptsOpenersPatterns8 = "prompts.openers.patterns.8"
  static let promptsOpenersPatterns9 = "prompts.openers.patterns.9"
  static let promptsOpenersPatterns10 = "prompts.openers.patterns.10"
  static let promptsOpenersFutureSelf1 = "prompts.openers.future_self.1"
  static let promptsOpenersFutureSelf2 = "prompts.openers.future_self.2"
  static let promptsOpenersFutureSelf3 = "prompts.openers.future_self.3"
  static let promptsOpenersFutureSelf4 = "prompts.openers.future_self.4"
  static let promptsOpenersFutureSelf5 = "prompts.openers.future_self.5"
  static let promptsOpenersFutureSelf6 = "prompts.openers.future_self.6"
  static let promptsOpenersFutureSelf7 = "prompts.openers.future_self.7"
  static let promptsOpenersFutureSelf8 = "prompts.openers.future_self.8"
  static let promptsOpenersFutureSelf9 = "prompts.openers.future_self.9"
  static let promptsOpenersFutureSelf10 = "prompts.openers.future_self.10"
  static let promptsOpenersReturning1 = "prompts.openers.returning.1"
  static let promptsOpenersReturning2 = "prompts.openers.returning.2"
  static let promptsOpenersReturning3 = "prompts.openers.returning.3"
  static let promptsOpenersReturning4 = "prompts.openers.returning.4"
  static let promptsOpenersReturning5 = "prompts.openers.returning.5"
  static let promptsOpenersReturning6 = "prompts.openers.returning.6"
  static let promptsOpenersReturning7 = "prompts.openers.returning.7"
  static let promptsOpenersReturning8 = "prompts.openers.returning.8"
  static let promptsOpenersReturning9 = "prompts.openers.returning.9"
  static let promptsOpenersReturning10 = "prompts.openers.returning.10"
  static let promptsOpenersContinue1 = "prompts.openers.continue.1"
  static let promptsOpenersContinue2 = "prompts.openers.continue.2"
  static let promptsOpenersContinue3 = "prompts.openers.continue.3"
  static let promptsOpenersContinue4 = "prompts.openers.continue.4"
  static let promptsOpenersContinue5 = "prompts.openers.continue.5"
  static let promptsOpenersContinue6 = "prompts.openers.continue.6"
  static let promptsOpenersContinue7 = "prompts.openers.continue.7"
  static let promptsOpenersContinue8 = "prompts.openers.continue.8"
  static let promptsOpenersContinue9 = "prompts.openers.continue.9"
  static let promptsOpenersContinue10 = "prompts.openers.continue.10"
  static let promptsOpenersBrainDump1 = "prompts.openers.brain_dump.1"
  static let promptsOpenersBrainDump2 = "prompts.openers.brain_dump.2"
  static let promptsOpenersBrainDump3 = "prompts.openers.brain_dump.3"
  static let promptsOpenersBrainDump4 = "prompts.openers.brain_dump.4"
  static let promptsOpenersBrainDump5 = "prompts.openers.brain_dump.5"
  static let promptsOpenersBrainDump6 = "prompts.openers.brain_dump.6"
  static let promptsOpenersBrainDump7 = "prompts.openers.brain_dump.7"
  static let promptsOpenersBrainDump8 = "prompts.openers.brain_dump.8"
  static let promptsOpenersBrainDump9 = "prompts.openers.brain_dump.9"
  static let promptsOpenersBrainDump10 = "prompts.openers.brain_dump.10"
}
